sudo: required
services:
  - docker

before_install:
  - docker build -t makanning/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true makanning/react-test npm test

after_success:
  - docker build -t makanning/multi-client ./client
  - docker build -t makanning/multi-nginx ./nginx
  - docker build -t makanning/multi-server ./server
  - docker build -t makanning/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push makanning/multi-client
  - docker push makanning/multi-nginx
  - docker push makanning/multi-server
  - docker push makanning/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-712940031129
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY